#Airbnb Data Cleaning project By Oluwatimilehin Olugbade

In [3]:
import pandas as pd

#Loading dataset using panda

In [ ]:
Data = pd.read_csv('Airbnb_Open_Data.csv', low_memory= False)

In [8]:
print(Data.head())

        id                                              NAME      host id  \
0  1001254                Clean & quiet apt home by the park  80014485718
1  1002102                             Skylit Midtown Castle  52335172823
2  1002403               THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3  1002755                                               NaN  85098326012
4  1003689  Entire Apt: Spacious Studio/Loft by central park  92037596077

  host_identity_verified host name neighbourhood group neighbourhood  \
0            unconfirmed  Madaline            Brooklyn    Kensington
1               verified     Jenna           Manhattan       Midtown
2                    NaN     Elise           Manhattan        Harlem
3            unconfirmed     Garry            Brooklyn  Clinton Hill
4               verified    Lyndon           Manhattan   East Harlem

        lat      long        country  ... service fee minimum nights  \
0  40.64749 -73.97237  United States  ...       $193            10.0
1  40.75362 -73.98377  United States  ...        $28            30.0
2  40.80902 -73.94190  United States  ...       $124             3.0
3  40.68514 -73.95976  United States  ...        $74            30.0
4  40.79851 -73.94399  United States  ...        $41            10.0

  number of reviews last review  reviews per month review rate number  \
0               9.0  10/19/2021               0.21                4.0
1              45.0   5/21/2022               0.38                4.0
2               0.0         NaN                NaN                5.0
3             270.0    7/5/2019               4.64                4.0
4               9.0  11/19/2018               0.10                3.0

  calculated host listings count  availability 365  \
0                            6.0             286.0
1                            2.0             228.0
2                            1.0             352.0
3                            1.0             322.0
4                            1.0             289.0

                                         house_rules license
0  Clean up and treat the home the way you'd like...     NaN
1  Pet friendly but please confirm with me if the...     NaN
2  I encourage you to use my kitchen, cooking and...     NaN
3                                                NaN     NaN
4  Please no smoking in the house, porch or on th...     NaN

[5 rows x 26 columns]

#Loading information about our dataset

In [9]:
print(Data.info())

<class 'pandas.DataFrame'>
RangeIndex: 102599 entries, 0 to 102598
Data columns (total 26 columns):
 #   Column                          Non-Null Count   Dtype
---  ------                          --------------   -----
 0   id                              102599 non-null  int64
 1   NAME                            102349 non-null  str
 2   host id                         102599 non-null  int64
 3   host_identity_verified          102310 non-null  str
 4   host name                       102193 non-null  str
 5   neighbourhood group             102570 non-null  str
 6   neighbourhood                   102583 non-null  str
 7   lat                             102591 non-null  float64
 8   long                            102591 non-null  float64
 9   country                         102067 non-null  str
 10  country code                    102468 non-null  str
 11  instant_bookable                102494 non-null  object
 12  cancellation_policy             102523 non-null  str
 13  room type                       102599 non-null  str
 14  Construction year               102385 non-null  float64
 15  price                           102352 non-null  str
 16  service fee                     102326 non-null  str
 17  minimum nights                  102190 non-null  float64
 18  number of reviews               102416 non-null  float64
 19  last review                     86706 non-null   str
 20  reviews per month               86720 non-null   float64
 21  review rate number              102273 non-null  float64
 22  calculated host listings count  102280 non-null  float64
 23  availability 365                102151 non-null  float64
 24  house_rules                     50468 non-null   str
 25  license                         2 non-null       str
dtypes: float64(9), int64(2), object(1), str(14)
memory usage: 20.4+ MB
None

#Deleting Redundant Columns: We identified several columns that are not necessary for our analysis because they contain little or no useful information. For example, the license column has about 99% missing values, which makes it uninformative for understanding the dataset. Therefore, such redundant columns can be removed to improve the quality of our dataset.

In [11]:
print(Data.columns)

Index(['id', 'NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license'],
      dtype='str')

#Using the output above we will create a list of columns to keep and columns to drop

In [ ]:
Columns_to_keep = ['NAME', 'host id', 'host_identity_verified', 'host name',
       'neighbourhood group', 'neighbourhood', 'lat', 'long', 'country',
       'country code', 'instant_bookable', 'cancellation_policy', 'room type',
       'Construction year', 'price', 'service fee', 'minimum nights',
       'number of reviews']
Columns_to_drop = ['id', 'last review', 'reviews per month',
       'review rate number', 'calculated host listings count',
       'availability 365', 'house_rules', 'license']

#Filtering our dataset to show only relevant columns

In [13]:
print(Data[Columns_to_keep])

                                                    NAME      host id  \
0                     Clean & quiet apt home by the park  80014485718
1                                  Skylit Midtown Castle  52335172823
2                    THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3                                                    NaN  85098326012
4       Entire Apt: Spacious Studio/Loft by central park  92037596077
...                                                  ...          ...
102594                        Spare room in Williamsburg  12312296767
102595                     Best Location near Columbia U  77864383453
102596                    Comfy, bright room in Brooklyn  69050334417
102597                  Big Studio-One Stop from Midtown  11160591270
102598                              585 sf Luxury Studio  68170633372

       host_identity_verified    host name neighbourhood group  \
0                 unconfirmed     Madaline            Brooklyn
1                    verified        Jenna           Manhattan
2                         NaN        Elise           Manhattan
3                 unconfirmed        Garry            Brooklyn
4                    verified       Lyndon           Manhattan
...                       ...          ...                 ...
102594               verified         Krik            Brooklyn
102595            unconfirmed        Mifan           Manhattan
102596            unconfirmed        Megan            Brooklyn
102597            unconfirmed  Christopher              Queens
102598            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country country code  \
0                Kensington  40.64749 -73.97237  United States           US
1                   Midtown  40.75362 -73.98377  United States           US
2                    Harlem  40.80902 -73.94190  United States           US
3              Clinton Hill  40.68514 -73.95976  United States           US
4               East Harlem  40.79851 -73.94399  United States           US
...                     ...       ...       ...            ...          ...
102594         Williamsburg  40.70862 -73.94651  United States           US
102595  Morningside Heights  40.80460 -73.96545  United States           US
102596           Park Slope  40.67505 -73.98045  United States           US
102597     Long Island City  40.74989 -73.93777  United States           US
102598      Upper West Side  40.76807 -73.98342  United States           US

       instant_bookable cancellation_policy        room type  \
0                 False              strict     Private room
1                 False            moderate  Entire home/apt
2                  True            flexible     Private room
3                  True            moderate  Entire home/apt
4                 False            moderate  Entire home/apt
...                 ...                 ...              ...
102594            False            flexible     Private room
102595             True            moderate     Private room
102596             True            moderate     Private room
102597             True              strict  Entire home/apt
102598            False            flexible  Entire home/apt

        Construction year    price service fee  minimum nights  \
0                  2020.0    $966        $193             10.0
1                  2007.0    $142         $28             30.0
2                  2005.0    $620        $124              3.0
3                  2005.0    $368         $74             30.0
4                  2009.0    $204         $41             10.0
...                   ...      ...         ...             ...
102594             2003.0    $844        $169              1.0
102595             2016.0    $837        $167              1.0
102596             2009.0    $988        $198              3.0
102597             2015.0    $546        $109              2.0
102598             2010.0  $1,032        $206              1.0

        number of reviews last review
0                     9.0  10/19/2021
1                    45.0   5/21/2022
2                     0.0         NaN
3                   270.0    7/5/2019
4                     9.0  11/19/2018
...                   ...         ...
102594                0.0         NaN
102595                1.0    7/6/2015
102596                0.0         NaN
102597                5.0  10/11/2015
102598                0.0         NaN

[102599 rows x 19 columns]

#We can clean our data by uisng the lists we created to drop(delete) the redundant columns. This is a permanent action unlike what we did before with the filter.

In [14]:
Data = Data.drop(columns= Columns_to_drop)
print(Data)

                                                    NAME      host id  \
0                     Clean & quiet apt home by the park  80014485718
1                                  Skylit Midtown Castle  52335172823
2                    THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3                                                    NaN  85098326012
4       Entire Apt: Spacious Studio/Loft by central park  92037596077
...                                                  ...          ...
102594                        Spare room in Williamsburg  12312296767
102595                     Best Location near Columbia U  77864383453
102596                    Comfy, bright room in Brooklyn  69050334417
102597                  Big Studio-One Stop from Midtown  11160591270
102598                              585 sf Luxury Studio  68170633372

       host_identity_verified    host name neighbourhood group  \
0                 unconfirmed     Madaline            Brooklyn
1                    verified        Jenna           Manhattan
2                         NaN        Elise           Manhattan
3                 unconfirmed        Garry            Brooklyn
4                    verified       Lyndon           Manhattan
...                       ...          ...                 ...
102594               verified         Krik            Brooklyn
102595            unconfirmed        Mifan           Manhattan
102596            unconfirmed        Megan            Brooklyn
102597            unconfirmed  Christopher              Queens
102598            unconfirmed      Rebecca           Manhattan

              neighbourhood       lat      long        country country code  \
0                Kensington  40.64749 -73.97237  United States           US
1                   Midtown  40.75362 -73.98377  United States           US
2                    Harlem  40.80902 -73.94190  United States           US
3              Clinton Hill  40.68514 -73.95976  United States           US
4               East Harlem  40.79851 -73.94399  United States           US
...                     ...       ...       ...            ...          ...
102594         Williamsburg  40.70862 -73.94651  United States           US
102595  Morningside Heights  40.80460 -73.96545  United States           US
102596           Park Slope  40.67505 -73.98045  United States           US
102597     Long Island City  40.74989 -73.93777  United States           US
102598      Upper West Side  40.76807 -73.98342  United States           US

       instant_bookable cancellation_policy        room type  \
0                 False              strict     Private room
1                 False            moderate  Entire home/apt
2                  True            flexible     Private room
3                  True            moderate  Entire home/apt
4                 False            moderate  Entire home/apt
...                 ...                 ...              ...
102594            False            flexible     Private room
102595             True            moderate     Private room
102596             True            moderate     Private room
102597             True              strict  Entire home/apt
102598            False            flexible  Entire home/apt

        Construction year    price service fee  minimum nights  \
0                  2020.0    $966        $193             10.0
1                  2007.0    $142         $28             30.0
2                  2005.0    $620        $124              3.0
3                  2005.0    $368         $74             30.0
4                  2009.0    $204         $41             10.0
...                   ...      ...         ...             ...
102594             2003.0    $844        $169              1.0
102595             2016.0    $837        $167              1.0
102596             2009.0    $988        $198              3.0
102597             2015.0    $546        $109              2.0
102598             2010.0  $1,032        $206              1.0

        number of reviews last review
0                     9.0  10/19/2021
1                    45.0   5/21/2022
2                     0.0         NaN
3                   270.0    7/5/2019
4                     9.0  11/19/2018
...                   ...         ...
102594                0.0         NaN
102595                1.0    7/6/2015
102596                0.0         NaN
102597                5.0  10/11/2015
102598                0.0         NaN

[102599 rows x 19 columns]

#Creating a standard column Title format for our dataset.

In [ ]:
new_column_format = []
for x in Data.columns:
    new_column_format.append(x.title().replace(" ", "_")) #Converts column names to Title Case and replace spaces with underscores

In [ ]:
Data = Data.columns = [new_column_format]
print(Data)

                                                    Name      Host_Id  \
0                     Clean & quiet apt home by the park  80014485718
1                                  Skylit Midtown Castle  52335172823
2                    THE VILLAGE OF HARLEM....NEW YORK !  78829239556
3                                                    NaN  85098326012
4       Entire Apt: Spacious Studio/Loft by central park  92037596077
...                                                  ...          ...
102053               Cozy bright room near Prospect Park  77326652202
102054         Private Bedroom with Amazing Rooftop View  45936254757
102055     Pretty Brooklyn One-Bedroom for 2 to 4 people  23801060917
102056        Room & private bathroom in historic Harlem  15593031571
102057                                   Rosalee Stewart  93578954226

       Host_Identity_Verified Host_Name Neighbourhood_Group  \
0                 unconfirmed  Madaline            Brooklyn
1                    verified     Jenna           Manhattan
2                         NaN     Elise           Manhattan
3                 unconfirmed     Garry            Brooklyn
4                    verified    Lyndon           Manhattan
...                       ...       ...                 ...
102053            unconfirmed    Mariam            Brooklyn
102054               verified      Trey            Brooklyn
102055               verified   Michael            Brooklyn
102056            unconfirmed   Shireen           Manhattan
102057               verified   Stanley           Manhattan

             Neighbourhood  Latitude Longitude        Country Country_Code  \
0               Kensington  40.64749 -73.97237  United States           US
1                  Midtown  40.75362 -73.98377  United States           US
2                   Harlem  40.80902 -73.94190  United States           US
3             Clinton Hill  40.68514 -73.95976  United States           US
4              East Harlem  40.79851 -73.94399  United States           US
...                    ...       ...       ...            ...          ...
102053            Flatbush  40.64945 -73.96108  United States           US
102054            Bushwick  40.69872 -73.92718  United States           US
102055  Bedford-Stuyvesant  40.67810 -73.90822  United States           US
102056              Harlem  40.81248 -73.94317  United States           US
102057              Harlem  40.81315 -73.94747  United States           US

       Instant_Bookable Cancellation_Policy        Room_Type  \
0                 False              strict     Private room
1                 False            moderate  Entire home/apt
2                  True            flexible     Private room
3                  True            moderate  Entire home/apt
4                 False            moderate  Entire home/apt
...                 ...                 ...              ...
102053             True            moderate     Private room
102054            False            flexible     Private room
102055             True            moderate  Entire home/apt
102056             True              strict     Private room
102057            False            flexible  Entire home/apt

       Construction_Year    Price Service_Fee Minimum_Nights Number_Of_Reviews
0                 2020.0    $966        $193            10.0               9.0
1                 2007.0    $142         $28            30.0              45.0
2                 2005.0    $620        $124             3.0               0.0
3                 2005.0    $368         $74            30.0             270.0
4                 2009.0    $204         $41            10.0               9.0
...                  ...      ...         ...            ...               ...
102053               NaN    $696          NaN            7.0              12.0
102054               NaN    $909          NaN            1.0              19.0
102055               NaN    $387          NaN            2.0              50.0
102056               NaN    $848          NaN            2.0               0.0
102057            2011.0  $1,128          NaN            4.0              22.0

[102058 rows x 18 columns]

#Rename two columns in our dataset(Lat and long)

In [21]:
Data.rename(columns={
    "Lat": "Latitude",
    "Long": "Longitude"
}, inplace=True)  #inplace helps to save our changes directly without having to recreate our data variable

#Checking and removing duplicates in our dataset

In [22]:
Data.duplicated().sum() #This Loads the number of duplicate rows in our dataset

np.int64(541)

In [24]:
Data.drop_duplicates(inplace=True) #This removes the duplicate rows from our dataset

In [25]:
Data.duplicated().sum() #Rechecking the dataset for duplicates

np.int64(0)

#Handling NaN(null) values in the dataset based on the importance and type of each column.

In [ ]:
print(Data.isna().sum()) #Loads the sum of null values in each column

Name                      250
Host_Id                     0
Host_Identity_Verified    289
Host_Name                 404
Neighbourhood_Group        29
Neighbourhood              16
Latitude                    8
Longitude                   8
Country                   532
Country_Code              131
Instant_Bookable          105
Cancellation_Policy        76
Room_Type                   0
Construction_Year         214
Price                     247
Service_Fee               273
Minimum_Nights            400
Number_Of_Reviews         183
dtype: int64

In [32]:
"""
Drop rows only where very important values are missing:
Price, Latitude, or Longitude are important for cost and location analysis. 
The number of null rows for lat and long is too small to hurt when dropped
We can keep or fill null price rows if we dont need to do a cost analysis or the number of rows missing is small,
in this case it's better to drop the price null rows as it will hinder visualization and comparing listings by price.
"""
Data.dropna(subset=["Price", "Latitude", "Longitude"])

KeyError: ['Price', 'Latitude', 'Longitude']

In [33]:
Data.columns

MultiIndex([(                  'Name',),
            (               'Host_Id',),
            ('Host_Identity_Verified',),
            (             'Host_Name',),
            (   'Neighbourhood_Group',),
            (         'Neighbourhood',),
            (              'Latitude',),
            (             'Longitude',),
            (               'Country',),
            (          'Country_Code',),
            (      'Instant_Bookable',),
            (   'Cancellation_Policy',),
            (             'Room_Type',),
            (     'Construction_Year',),
            (                 'Price',),
            (           'Service_Fee',),
            (        'Minimum_Nights',),
            (     'Number_Of_Reviews',)],
           )

In [ ]:
#dropna failed because the columns are stored as a multi index so i will flatten them to remove the extra column level and make column names normal
Data.columns = Data.columns.get_level_values(0) 
Data.dropna(subset=["Price", "Latitude", "Longitude"], inplace=True)

In [41]:
# Fill numeric columns with median
numeric_cols = ["Service_Fee", "Minimum_Nights", "Construction_Year", "Number_Of_Reviews"]
for col in numeric_cols:
    Data[col] = Data[col].fillna(Data[col].median())

TypeError: Cannot perform reduction 'median' with string dtype

In [ ]:
"""
The code above throws an error because the service fee column has a dollar sign  and that makes the column a string.
i will fix this then reload the code.
"""
# Remove $ and convert to numeric, the 'errors' is incase the column has missing values or bad text
Data["Service_Fee"] = pd.to_numeric(Data["Service_Fee"].replace("[$,]", "", regex=True), errors="coerce")  
numeric_cols = ["Service_Fee", "Minimum_Nights", "Construction_Year", "Number_Of_Reviews"]
for col in numeric_cols:
    Data[col] = Data[col].fillna(Data[col].median())

In [44]:
# Fill text columns with "Unknown"
Data["Host_Name"] = Data["Host_Name"].fillna("Unknown")
Data["Country"] = Data["Country"].fillna("Unknown")
Data["Name"] = Data["Name"].fillna("Unknown")
Data["Neighbourhood_Group"] = Data["Neighbourhood_Group"].fillna('Unknown')
Data["Neighbourhood"] = Data["Neighbourhood"].fillna("Unknown")
Data["Country_Code"] = Data["Country_Code"].fillna('unknown')

In [46]:
# Fill remaining categorical columns with mode
categorical_cols = ["Host_Identity_Verified", "Instant_Bookable", "Cancellation_Policy"]

for col in categorical_cols:
    Data[col] = Data[col].fillna(Data[col].mode()[0])

In [47]:
Data.isna().sum() #Rechecking the sum of the null values across columns to see if the changes reflected

Name                      0
Host_Id                   0
Host_Identity_Verified    0
Host_Name                 0
Neighbourhood_Group       0
Neighbourhood             0
Latitude                  0
Longitude                 0
Country                   0
Country_Code              0
Instant_Bookable          0
Cancellation_Policy       0
Room_Type                 0
Construction_Year         0
Price                     0
Service_Fee               0
Minimum_Nights            0
Number_Of_Reviews         0
dtype: int64

#Cleaning Individual Columns

In [ ]:
# changing the values in Host_identity_verified to uppercase letters
Data['Host_Identity_Verified'] = Data['Host_Identity_Verified'].str.upper()

In [52]:
Data['Host_Identity_Verified']

0         UNCONFIRMED
1            VERIFIED
2         UNCONFIRMED
3         UNCONFIRMED
4            VERIFIED
             ...
102053    UNCONFIRMED
102054       VERIFIED
102055       VERIFIED
102056    UNCONFIRMED
102057       VERIFIED
Name: Host_Identity_Verified, Length: 101803, dtype: str

In [53]:
#The price column has the dollar sign, which makes it a string value and will make price analysis almost impossible, so I will fix that.
Data["Price"] = pd.to_numeric(Data["Price"].replace("[$,]", "", regex=True), errors="coerce") 
Data['Price']

0          966
1          142
2          620
3          368
4          204
          ...
102053     696
102054     909
102055     387
102056     848
102057    1128
Name: Price, Length: 101803, dtype: int64

In [56]:
#The construction year is a float value with decimal, I think its best to convert it to an integer
Data["Construction_Year"] = Data["Construction_Year"].astype(int)
Data["Construction_Year"]

0         2020
1         2007
2         2005
3         2005
4         2009
          ...
102053    2012
102054    2012
102055    2012
102056    2012
102057    2011
Name: Construction_Year, Length: 101803, dtype: int64

In [58]:
Data['Neighbourhood_Group'].unique()
"""
There's 8 distinct values in the Neighbourhood_Group column instead of 6 because "Brooklyn" and "Manhattan" were spelled wrong in some rows. 
I will be fixing this so it doens't affect our analysis
"""
Data["Neighbourhood_Group"] = Data["Neighbourhood_Group"].replace({
    "brookln": "Brooklyn",
    "manhatan": "Manhattan"
})  # Correct misspelled neighbourhood names

In [59]:
Data['Neighbourhood_Group'].unique() #rechecking to confirm our changes were effected

<StringArray>
['Brooklyn', 'Manhattan', 'Queens', 'Unknown', 'Staten Island', 'Bronx']
Length: 6, dtype: str

In [61]:
Data['Room_Type'].unique()

<StringArray>
['Private room', 'Entire home/apt', 'Shared room', 'Hotel room']
Length: 4, dtype: str

In [ ]:
"""We have some rows with less than 0 minimum night, negative values in Minimum_Nights are not logically valid,
so they are likely data entry errors and should be cleaned
"""
Data[Data["Minimum_Nights"] < 0]

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Latitude,Longitude,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews
176,BROOKLYN VICTORIAN STYLE SUITE.....,83631499592,UNCONFIRMED,Frederick,Brooklyn,Fort Greene,40.69098,-73.97113,United States,US,False,flexible,Private room,2008,1155,231.0,-10.0,213.0
352,"Beautiful, Bright’s, Warm & Spacious 1.5BR Apt",2227683633,UNCONFIRMED,Grant,Brooklyn,Crown Heights,40.67174,-73.95663,Unknown,unknown,False,moderate,Entire home/apt,2009,73,15.0,-5.0,104.0
398,SUPER BIG AND COZY PRIVATE BEDROOM,50336791874,VERIFIED,Tucker,Brooklyn,Kensington,40.64302,-73.97255,United States,US,False,flexible,Private room,2015,779,156.0,-1.0,82.0
421,Charming Nolita Apartment!!,7389895192,VERIFIED,Belinda,Manhattan,Nolita,40.72094,-73.99706,United States,US,False,flexible,Entire home/apt,2008,874,175.0,-10.0,68.0
441,Cozy apartment in a brownstone,81186886194,VERIFIED,Adelaide,Manhattan,Harlem,40.80497,-73.95016,United States,US,False,moderate,Entire home/apt,2021,920,184.0,-12.0,203.0
478,Charming upper west side apartment,89878315253,UNCONFIRMED,Alen,Manhattan,Upper West Side,40.77886,-73.98042,United States,US,True,strict,Entire home/apt,2022,410,82.0,-2.0,129.0
525,Chateau Style Brooklyn Loft for Singles or Cou...,2631536622,VERIFIED,Carlos,Brooklyn,Bedford-Stuyvesant,40.68967,-73.95445,United States,US,False,moderate,Entire home/apt,2022,413,83.0,-3.0,42.0
42446,"Cozy room in bright, spacious apartment",84040511136,VERIFIED,Steven,Bronx,Hunts Point,40.81731,-73.89052,United States,US,False,moderate,Private room,2003,1200,240.0,-1223.0,0.0
42500,2bd BOUTIQUE Apartament in the heart of MANHA...,2679070022,UNCONFIRMED,Tom,Manhattan,Hell's Kitchen,40.76694,-73.98773,United States,US,True,flexible,Entire home/apt,2009,711,142.0,-365.0,13.0
42538,Newly Renovated Garden Apartment,98469733112,VERIFIED,Margie,Brooklyn,Bedford-Stuyvesant,40.68470,-73.94350,United States,US,True,moderate,Entire home/apt,2022,85,17.0,-200.0,3.0
69749,Amazing location! 10ft from L train,62132542936,VERIFIED,Giorgia & Benjamin,Brooklyn,Williamsburg,40.71534,-73.94906,United States,US,False,moderate,Private room,2012,328,66.0,-125.0,146.0
91271,Beautiful modern & large 2 bedroom,13861414317,UNCONFIRMED,Vikas,Manhattan,Midtown,40.74433,-73.98318,United States,US,False,moderate,Entire home/apt,2007,772,154.0,-10.0,0.0
91357,Cozy Brooklyn Apartment,63988893317,VERIFIED,Daniella,Brooklyn,Gowanus,40.67070,-73.99118,United States,US,True,moderate,Shared room,2014,1177,235.0,-10.0,9.0

In [ ]:
(Data["Minimum_Nights"] < 0).sum() # Count rows where Minimum_Nights is less than zero

np.int64(13)

In [67]:
Data = Data[Data["Minimum_Nights"] >= 0]  # Remove rows with negative minimum nights

In [70]:
#Exporting cleaned data to a csv file
Data.to_csv("Airbnb_Cleaned_Data.csv", index=False)

In [ ]:
#Loading csv file
pd.read_csv('Airbnb_Cleaned_Data.csv')

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Latitude,Longitude,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020,966,193.0,10.0,9.0
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007,142,28.0,30.0,45.0
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNCONFIRMED,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005,620,124.0,3.0,0.0
3,Unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005,368,74.0,30.0,270.0
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009,204,41.0,10.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101785,Cozy bright room near Prospect Park,77326652202,UNCONFIRMED,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,2012,696,125.0,7.0,12.0
101786,Private Bedroom with Amazing Rooftop View,45936254757,VERIFIED,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,2012,909,125.0,1.0,19.0
101787,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,VERIFIED,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,2012,387,125.0,2.0,50.0
101788,Room & private bathroom in historic Harlem,15593031571,UNCONFIRMED,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,2012,848,125.0,2.0,0.0
101789,Rosalee Stewart,93578954226,VERIFIED,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011,1128,125.0,4.0,22.0

In [73]:
#Exporting cleaned dataset to an excel file
Data.to_excel("Airbnb_Cleaned_Data.xlsx", index= False)

In [ ]:
#loading excel file
pd.read_excel('Airbnb_Cleaned_Data.xlsx')

,Name,Host_Id,Host_Identity_Verified,Host_Name,Neighbourhood_Group,Neighbourhood,Latitude,Longitude,Country,Country_Code,Instant_Bookable,Cancellation_Policy,Room_Type,Construction_Year,Price,Service_Fee,Minimum_Nights,Number_Of_Reviews
0,Clean & quiet apt home by the park,80014485718,UNCONFIRMED,Madaline,Brooklyn,Kensington,40.64749,-73.97237,United States,US,False,strict,Private room,2020,966,193,10,9
1,Skylit Midtown Castle,52335172823,VERIFIED,Jenna,Manhattan,Midtown,40.75362,-73.98377,United States,US,False,moderate,Entire home/apt,2007,142,28,30,45
2,THE VILLAGE OF HARLEM....NEW YORK !,78829239556,UNCONFIRMED,Elise,Manhattan,Harlem,40.80902,-73.94190,United States,US,True,flexible,Private room,2005,620,124,3,0
3,Unknown,85098326012,UNCONFIRMED,Garry,Brooklyn,Clinton Hill,40.68514,-73.95976,United States,US,True,moderate,Entire home/apt,2005,368,74,30,270
4,Entire Apt: Spacious Studio/Loft by central park,92037596077,VERIFIED,Lyndon,Manhattan,East Harlem,40.79851,-73.94399,United States,US,False,moderate,Entire home/apt,2009,204,41,10,9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101785,Cozy bright room near Prospect Park,77326652202,UNCONFIRMED,Mariam,Brooklyn,Flatbush,40.64945,-73.96108,United States,US,True,moderate,Private room,2012,696,125,7,12
101786,Private Bedroom with Amazing Rooftop View,45936254757,VERIFIED,Trey,Brooklyn,Bushwick,40.69872,-73.92718,United States,US,False,flexible,Private room,2012,909,125,1,19
101787,Pretty Brooklyn One-Bedroom for 2 to 4 people,23801060917,VERIFIED,Michael,Brooklyn,Bedford-Stuyvesant,40.67810,-73.90822,United States,US,True,moderate,Entire home/apt,2012,387,125,2,50
101788,Room & private bathroom in historic Harlem,15593031571,UNCONFIRMED,Shireen,Manhattan,Harlem,40.81248,-73.94317,United States,US,True,strict,Private room,2012,848,125,2,0
101789,Rosalee Stewart,93578954226,VERIFIED,Stanley,Manhattan,Harlem,40.81315,-73.94747,United States,US,False,flexible,Entire home/apt,2011,1128,125,4,22